# Generated by Django 4.2.7 on 2024-03-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_category_job_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='education_experience',
            field=models.TextField(max_length=10000, verbose_name='Education & Experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='knowledge_requirements',
            field=models.TextField(max_length=10000, verbose_name='Knowledge & Requirements'),
        ),
    ]
