# Generated by Django 4.2.7 on 2024-03-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='jobs.job'),
        ),
    ]
